### ISSUE TITLE
TBB+NEON+VFVP3 vs NEON+VFVP3

### ISSUE THREAD

**Issue by Favi0** [abhiTronix/OpenCV_Raspberry_pi_TBB#3]
Hey abhi i finally managed to install neon on an older version of opencv 

i would like to ask you if you have measured the performance difference with and without TBB? also i saw in your youtube channel that you have installed OPENCL for the gpu , is it really usable?

**Comment by abhiTronix** [comment]
@Favi0 
My latest binaries include OpenCL +TBB+NEON+VFVP3 support to enable maximum performance in Raspberry Pi platform with various OpenCV and deep learning applications.

>  i would like to ask you if you have measured the performance difference with and without TBB?

Yes, You can aspect almost 1.5x~3x performance boost, achieved by parallelizing your code execution by enabling compiler-level optimizations through features like scalable memory allocation and task scheduling in TBB. This enables you to multiprocess your tasks without changing your code and use all four cores on Raspberry Pi and thus reducing chances of CPU throttling while performing heavy computational tasks. Here is an example video(Check CPU utilization): https://youtu.be/HBxyQU-c62o

> i saw in your youtube channel that you have installed OPENCL for the gpu , is it really usable?

OpenCL consists of an applications programming interface (API) for coordinating parallel computation across heterogeneous processors and a cross-platform programming language with a well-specified computation environment. With OpenCL, the goal is often to represent parallelism programmatically at the finest granularity possible. OpenCL provides a standard interface for parallel computing using task- and data-based parallelism. This feature makes OpenCL ideal to solve the complex computational problem by utilizing multiple compute resources. Here is an example: https://github.com/doe300/VC4CL/issues/29#issuecomment-464488265

**Comment by Favi0** [comment]
wow that sounds amazing ! that would open a door for many kind of new developments on the pi
