### ISSUE TITLE
I think I installed everything correctly in Raspberry Pi Stretch

### ISSUE THREAD

**Issue by steven5clu884** [abhiTronix/OpenCV_Raspberry_pi_TBB#5]
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libtesseract.so.4: cannot open shared object file: No such file or directory
>>>

**Comment by abhiTronix** [comment]
@steven5clu884 This error is due to libtesseract recently got updated to `libtesseract.so.5`. Kindly follow [these updated instructions](https://github.com/abhiTronix/OpenCV_Raspberry_pi_TBB/issues/1#issue-391020295) to solve this problem. Goodluck.

**Comment by abhiTronix** [comment]
Closed. Feel free to reopen if something doesn't work for you.

**Comment by abhiTronix** [comment]
Closed. Feel free to reopen if it still doesn't work for you.
