### ISSUE TITLE
OpenCV_Raspberry_pi_TBB For Python3

### ISSUE THREAD

**Issue by Akhtar303** [abhiTronix/OpenCV_Raspberry_pi_TBB#6]
Hi @abhiTronix Thanks to share the great project
I am Installing optimized opencv for python3.7.3
**sudo dpkg -i opencv_4.0.0-pre-demo_armhf.deb**

but it's working with python2.7 not for python3.7.3 
I am also trying  to create link but failled
i.e
**sudo ln -sv /usr/local/lib/python2.7/dist-packages/cv2/python-2.7/cv2.so**
Kindly suggest me to changes to resolve this issue.
Thanks

**Comment by abhiTronix** [comment]
> I am also trying to create link but failled
> i.e
> sudo ln -sv /usr/local/lib/python2.7/dist-packages/cv2/python-2.7/cv2.so

@Akhtar303 This will not work as this `.so` file is meant for Python 2.7 and not python 3+.

Try this instead:

```sh
sudo ln -sf  /usr/lib/arm-linux-gnueabihf/libpython3.5m.so /usr/local/lib/python3.7.3/dist-packages/
```
**But remember this file is made for Raspbian Stretch only, If you're on Buster this may not work!**
